#!/usr/bin/env python3
"""Deterministic scope engine and prevention tooling. stdlib only.

Two layers, both driven by the task contract (scripts/contracts.py):

  Layer A - PREVENTION (mechanical, where the harness genuinely supports it)
    * `install-hook`   a run-owned pre-commit gate installed *only* into the worker's worktree via
                       `git config --worktree core.hooksPath` (verified on git 2.55.0: the linked
                       worktree is blocked, the shared checkout is untouched). Any commit containing
                       a path outside write_scope, or inside forbidden_scope, is refused.
    * `plan`           per-kind write-boundary hardening generated from the contract. Adapters are
                       evidence-based: only mechanisms verified on this host are claimed, and
                       `verify-launch` re-proves the effective rules before dispatch.
                       `OPENCODE_PERMISSION` / `OPENCODE_CONFIG_CONTENT` carry an edit deny-by-default
                       rule set that overrides a project config (verified on opencode 1.18.30);
                       a plain `OPENCODE_CONFIG` file does NOT (project config wins) and is therefore
                       never used alone.
                       Kinds without a verified sub-path mechanism are reported as
                       `prevention: none` - no invented support.

  Layer B - DETECTION (always, independent of prevention)
    * `check`          compares `git diff --name-only <base>...<head>` against write_scope and
                       forbidden_scope and returns SCOPE: PASS/FAIL (text or `--json`).
    * `staged`         the same comparison for the staged index; used by the pre-commit gate.

Nothing here judges code quality; nothing here integrates branches. Exit codes: 0 pass, 1
violation/failed check, 2 usage error.
"""

from __future__ import annotations

import argparse
import json
import re
import shlex
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from contracts import (  # noqa: E402
    load_structured_text, normalize_contract, scope_patterns, validate_contract, now,
)

# Generated by the toolchain, never authored by the worker: a live run flagged `__pycache__/` as a
# scope violation on both workers, which is noise that hides real violations. A run can add more
# with `ignore_scope` in the contract.
ALWAYS_IGNORED = [
    ".orchestrator/**", ".git/**", "**/.opencode/**",
    "**/__pycache__/**", "**/*.pyc", "**/*.pyo",
    "**/node_modules/**", "**/.venv/**", "**/venv/**",
    "**/.pytest_cache/**", "**/.mypy_cache/**", "**/.ruff_cache/**", "**/.cache/**",
    "**/dist/**", "**/build/**", "**/target/**", "**/*.egg-info/**",
]
GLOB_CHARS = "*?["


# --------------------------------------------------------------------------- glob matching

def normalize_pattern(pattern: str, *, directory: bool = True) -> str:
    """Accept directories, `./x`, `x/` and glob forms; return a canonical glob.

    A bare path is ambiguous: `src/app` is a directory, `src/stats.py` is a file. With
    `directory=True` (the default, used for directory semantics) a bare path becomes `p/**`;
    with `directory=False` it stays literal, which is what makes a single-file `write_scope`
    match the file itself. `path_matches` tries both, so either meaning works.
    """
    p = str(pattern).strip().replace("\\", "/")
    while p.startswith("./"):
        p = p[2:]
    p = p.rstrip("/")
    if not p:
        return "**"
    if not any(c in p for c in GLOB_CHARS):
        return p + "/**" if directory else p
    return p


def pattern_to_regex(pattern: str, *, directory: bool = True) -> re.Pattern:
    """Translate a glob into a regex. `**` crosses path separators; `*` and `?` do not."""
    p = normalize_pattern(pattern, directory=directory)
    out = ["^"]
    i = 0
    while i < len(p):
        ch = p[i]
        if ch == "*":
            if i + 1 < len(p) and p[i + 1] == "*":
                nxt = p[i + 2: i + 3]
                if nxt == "/":
                    out.append("(?:.*/)?")
                    i += 3
                    continue
                out.append(".*")
                i += 2
                continue
            out.append("[^/]*")
            i += 1
            continue
        if ch == "?":
            out.append("[^/]")
            i += 1
            continue
        out.append(re.escape(ch))
        i += 1
    out.append("$")
    return re.compile("".join(out))


def path_matches(path: str, pattern: str) -> bool:
    # Strip ONE leading "./" — `lstrip("./")` also ate the dot of dot-directories, so
    # `.pytest_cache/x` was normalised to `pytest_cache/x` and stopped matching any pattern.
    p = str(path).strip()
    while p.startswith("./"):
        p = p[2:]
    p = p.lstrip("/").replace("\\", "/")
    if pattern in ("**", "**/*"):
        return True
    if pattern_to_regex(pattern).match(p):
        return True
    # the same bare path also means "this file": `write_scope: [src/stats.py]` must match the file
    return bool(pattern_to_regex(pattern, directory=False).match(p))


def matches_any(path: str, patterns) -> bool:
    return any(path_matches(path, p) for p in patterns)


# ------------------------------------------------------------------- overlap (v1.4)
# Collisions are authored during planning: two live writers whose scopes can match the
# same path are a merge conflict on a timer. Catching it here costs nothing; catching it
# at merge costs a whole task.

CATCH_ALL = {"**", "**/*", "*", "./**", "./*"}


def literal_prefix(pattern: str) -> str:
    """The fixed part of a pattern before its first glob character (its directory lead)."""
    p = normalize_pattern(pattern)
    for i, ch in enumerate(p):
        if ch in GLOB_CHARS:
            return p[:i]
    return p


def scopes_overlap(a: str, b: str) -> tuple:
    """(overlap, confidence) for two write-scope patterns; confidence: definite|possible|none.

    Conservative on purpose: `possible` still requires a decision from the orchestrator
    (serialise the tasks or record why the overlap is harmless).
    """
    pa, pb = normalize_pattern(a), normalize_pattern(b)
    if pa == pb:
        return True, "definite"
    if pa in CATCH_ALL or pb in CATCH_ALL:
        return True, "possible"
    la, lb = literal_prefix(pa), literal_prefix(pb)
    if not la or not lb:
        return True, "possible"
    if la.startswith(lb) or lb.startswith(la):
        return True, "definite"
    return False, "none"


def pairwise_overlaps(tasks: list) -> list:
    """Every colliding pair among the given tasks (each with task_id + write_scope)."""
    collisions = []
    for i, a in enumerate(tasks):
        for b in tasks[i + 1:]:
            for pa in (a.get("write_scope") or []):
                for pb in (b.get("write_scope") or []):
                    over, confidence = scopes_overlap(pa, pb)
                    if over:
                        collisions.append({
                            "tasks": [a.get("task_id") or a.get("id"), b.get("task_id") or b.get("id")],
                            "patterns": [pa, pb],
                            "confidence": confidence,
                        })
    collisions.sort(key=lambda c: (c["confidence"] != "definite", c["tasks"]))
    return collisions


def classify_paths(paths, contract: dict) -> dict:
    """Split changed paths into allowed / unexpected / forbidden / ignored. Pure and deterministic."""
    write_scope = scope_patterns(contract, "write_scope")
    forbidden = scope_patterns(contract, "forbidden_scope")
    ignore = ALWAYS_IGNORED + scope_patterns(contract, "ignore_scope")
    out = {"allowed": [], "unexpected": [], "forbidden": [], "ignored": []}
    violations = []
    for raw in sorted({str(p).strip() for p in paths if str(p).strip()}):
        if matches_any(raw, ignore):
            out["ignored"].append(raw)
            continue
        if matches_any(raw, forbidden):
            out["forbidden"].append(raw)
            violations.append({"path": raw, "kind": "forbidden",
                               "detail": "matches forbidden_scope"})
            continue
        if matches_any(raw, write_scope):
            out["allowed"].append(raw)
            continue
        out["unexpected"].append(raw)
        violations.append({"path": raw, "kind": "unexpected",
                           "detail": "outside write_scope"})
    out["violations"] = violations
    return out


# --------------------------------------------------------------------------- git helpers

def git(repo, args: list) -> tuple[int, str]:
    try:
        p = subprocess.run(["git", *args], cwd=str(repo), capture_output=True, text=True,
                           timeout=120)
        return p.returncode, (p.stdout or p.stderr).strip()
    except (OSError, subprocess.TimeoutExpired) as exc:
        return 127, str(exc)


def changed_paths(repo, base: str, head: str = "HEAD") -> tuple[int, list, str]:
    code, out = git(repo, ["diff", "--name-only", f"{base}...{head}"])
    if code != 0:
        return code, [], out
    return 0, [ln for ln in out.splitlines() if ln.strip()], ""


def staged_paths(repo) -> tuple[int, list, str]:
    code, out = git(repo, ["diff", "--cached", "--name-only"])
    if code != 0:
        return code, [], out
    return 0, [ln for ln in out.splitlines() if ln.strip()], ""


def dirty_paths(repo) -> list:
    """Every path git reports as changed, including individual untracked files (not the dir)."""
    code, out = git(repo, ["status", "--porcelain", "--untracked-files=all"])
    if code != 0:
        return []
    paths = []
    for line in out.splitlines():
        chunk = line[3:].strip()
        if " -> " in chunk:
            chunk = chunk.split(" -> ", 1)[1]
        if chunk:
            p = chunk.strip('"')
            if not matches_any(p, ALWAYS_IGNORED):      # build/cache output is not the worker's dirt
                paths.append(p)
    return paths


def worktree_clean(path) -> bool | None:
    """True when nothing the worker authored is left uncommitted (build/cache output does not count)."""
    code, out = git(path, ["status", "--porcelain"])
    if code != 0:
        return None
    for line in out.splitlines():
        chunk = line[3:].strip()
        if " -> " in chunk:
            chunk = chunk.split(" -> ", 1)[1]
        if chunk and not matches_any(chunk.strip('"'), ALWAYS_IGNORED):
            return False
    return True


def commit_exists(repo, sha: str) -> bool:
    if not sha:
        return False
    code, _ = git(repo, ["cat-file", "-e", f"{sha}^{{commit}}"])
    return code == 0


# --------------------------------------------------------------------------- checks

def check_scope(contract: dict, *, repo, base: str | None = None, head: str | None = None,
                include_dirty: bool = False, paths=None) -> dict:
    """Compare the contract against real changed paths. Returns a machine-readable verdict."""
    repo = Path(repo)
    base = base or contract.get("base_commit")
    head = head or contract.get("branch") or "HEAD"
    result = {
        "task_id": contract.get("task_id"),
        "repo": str(repo),
        "base": base,
        "head": head,
        "status": "UNKNOWN",
        "changed": [], "allowed": [], "unexpected": [], "forbidden": [], "ignored": [],
        "violations": [],
        "include_dirty": bool(include_dirty),
        "checked_at": now(),
    }
    if paths is None:
        if not base:
            result["error"] = "contract has no base_commit and none was given (--base)"
            return result
        code, paths, err = changed_paths(repo, base, head)
        if code != 0:
            result["error"] = f"git diff failed: {err[:200]}"
            return result
    paths = list(paths)
    if include_dirty:
        for p in dirty_paths(repo):
            if p not in paths:
                paths.append(p)
    cls = classify_paths(paths, contract)
    result.update({"changed": sorted(paths), **{k: v for k, v in cls.items()}})
    result["status"] = "PASS" if not cls["violations"] else "FAIL"
    return result


def render_check(result: dict) -> str:
    if result.get("error"):
        return f"SCOPE: UNKNOWN\n\nerror: {result['error']}"
    lines = [f"SCOPE: {result['status']}", ""]
    lines.append(f"task: {result.get('task_id')}  base: {result.get('base')}  head: {result.get('head')}")
    lines.append(f"changed: {len(result['changed'])} path(s)")
    if result["unexpected"]:
        lines += ["", "unexpected:"] + [f"- {p}" for p in result["unexpected"]]
    if result["forbidden"]:
        lines += ["", "forbidden:"] + [f"- {p}" for p in result["forbidden"]]
    if result["ignored"]:
        lines += ["", "ignored (declared):"] + [f"- {p}" for p in result["ignored"]]
    if result["status"] == "PASS":
        lines += ["", "every changed path is inside write_scope"]
    else:
        lines += ["", "SCOPE_VIOLATION: the task may not be integrated until this is resolved"]
    return "\n".join(lines)


# --------------------------------------------------------------------------- contract resolution

def load_contract_file(path) -> dict:
    text = Path(path).read_text(encoding="utf-8")
    data = load_structured_text(text)
    if not isinstance(data, dict):
        raise ValueError(f"{path}: contract is not a mapping")
    return normalize_contract(data)


def contract_path_for(repo, task_id: str) -> Path | None:
    base = Path(repo) / ".orchestrator" / "contracts" / task_id
    for suffix in (".json", ".yaml", ".yml"):
        candidate = base.with_suffix(suffix)
        if candidate.is_file():
            return candidate
    return None


def resolve_contract(repo, file=None, task_id=None) -> dict:
    if file:
        return load_contract_file(file)
    if task_id:
        path = contract_path_for(repo, task_id)
        if path is None:
            raise FileNotFoundError(f"no contract for task {task_id!r} under "
                                    f"{Path(repo) / '.orchestrator' / 'contracts'}")
        return load_contract_file(path)
    raise ValueError("pass --contract FILE or --task-id ID")


# --------------------------------------------------------------------------- Layer A: hook gate

HOOK_TEMPLATE = """#!/bin/sh
# Generated by herdr-orchestrator scope_guard.py for task {task_id!r} (run {run_ref}).
# Refuses a commit whose staged paths leave the contracted write_scope.
# Do not edit: regenerate with `scope_guard.py install-hook`.
set -u
GUARD={guard!r}
CONTRACT={contract!r}
REPO={repo!r}
WORKTREE={worktree!r}
CHAIN={chain!r}
if [ -x "$CHAIN" ]; then
    "$CHAIN" "$@" || exit $?
fi
if command -v python3 >/dev/null 2>&1; then PY=python3; else PY=python; fi
out=$("$PY" "$GUARD" staged --contract "$CONTRACT" --repo "$REPO" --worktree "$WORKTREE" 2>&1) || {{
    echo "$out" >&2
    echo "SCOPE_GUARD: commit refused (scope violation). Report the blocked reason to the" >&2
    echo "orchestrator; do not widen your scope and do not use --no-verify." >&2
    exit 1
}}
exit 0
"""


def install_hook(contract: dict, worktree, repo, *, guards_dir=None, hooks_dir=None,
                 chain_existing=True) -> dict:
    """Install the run-owned pre-commit gate for one worktree.

    Uses `extensions.worktreeConfig` + `git config --worktree core.hooksPath`, so the shared
    checkout and the project's own hooks path are left alone (verified mechanism, git >= 2.36).
    """
    worktree = Path(worktree)
    repo = Path(repo)
    task_id = str(contract.get("task_id") or "task")
    guards = Path(guards_dir) if guards_dir else repo / ".orchestrator" / "guards" / task_id
    hooks = Path(hooks_dir) if hooks_dir else guards / "hooks"
    hooks.mkdir(parents=True, exist_ok=True)

    code, out = git(worktree, ["rev-parse", "--is-inside-work-tree"])
    if code != 0 or out != "true":
        return {"installed": False, "error": f"{worktree} is not a git working tree"}

    # contract snapshot next to the guard so the hook never depends on mutable orchestration state
    contract_file = guards / "contract.json"
    contract_file.write_text(json.dumps(contract, indent=2) + "\n", encoding="utf-8")

    orig = git(worktree, ["config", "--get", "core.hooksPath"])[1].strip()
    code, common = git(worktree, ["rev-parse", "--git-common-dir"])
    common_dir = Path(common) if code == 0 else repo / ".git"
    if not common_dir.is_absolute():
        common_dir = (Path(common_dir) if common_dir.is_absolute() else worktree / common_dir)
    chain = ""
    if chain_existing:
        if orig:
            chain = str(Path(orig) / "pre-commit")
        else:
            chain = str(common_dir / "hooks" / "pre-commit")
        if not (Path(chain).is_file() and Path(chain).stat().st_mode & 0o111):
            chain = ""

    hook = hooks / "pre-commit"
    hook.write_text(
        HOOK_TEMPLATE.format(task_id=task_id, guard=str(Path(__file__).resolve()),
                             contract=str(contract_file), repo=str(repo), worktree=str(worktree),
                             chain=chain, run_ref=(contract.get("branch") or "run")),
        encoding="utf-8")
    hook.chmod(0o755)

    wt_config = {"extensions.worktreeConfig_was_set": True}
    code, current = git(worktree, ["config", "--get", "extensions.worktreeConfig"])
    if code != 0 or current.strip() != "true":
        git(repo, ["config", "extensions.worktreeConfig", "true"])
        wt_config["extensions.worktreeConfig_was_set"] = False

    # Write the worktree-scoped config EXPLICITLY into that worktree's gitdir. `git config
    # --worktree` resolves the target from the process environment, and a stale GIT_DIR (or the
    # wrong cwd) silently writes into another worktree's config — observed once in a live run,
    # where two workers ended up sharing one guard. Explicit file, then verify.
    code, gitdir = git(worktree, ["rev-parse", "--git-dir"])
    if code != 0:
        return {"installed": False, "error": f"cannot resolve the worktree gitdir: {gitdir[:200]}"}
    gitdir_path = Path(gitdir)
    if not gitdir_path.is_absolute():
        gitdir_path = (worktree / gitdir_path).resolve()
    wt_config_file = gitdir_path / "config.worktree"
    code, out = git(worktree, ["config", "--file", str(wt_config_file),
                               "core.hooksPath", str(hooks)])
    if code != 0:
        return {"installed": False, "error": f"git config --file failed: {out[:200]}"}
    code, effective = git(worktree, ["config", "--get", "core.hooksPath"])
    if code != 0 or effective.strip() != str(hooks):
        return {"installed": False, "worktree": str(worktree),
                "error": f"verification failed: this worktree reports {effective.strip()!r}, expected "
                         f"{str(hooks)!r} — refusing to claim prevention that is not in force"}
    return {
        "installed": True,
        "task_id": task_id,
        "worktree": str(worktree),
        "hooks_dir": str(hooks),
        "hook": str(hook),
        "contract_snapshot": str(contract_file),
        "effective_hooks_path": effective.strip(),
        "worktree_config_file": str(wt_config_file),
        "chained_project_hook": chain or None,
        "mechanism": "git --worktree core.hooksPath (worktree-scoped)",
        "shared_config_touched": ([] if wt_config["extensions.worktreeConfig_was_set"]
                                  else ["extensions.worktreeConfig=true (additive; the run records "
                                        "it and may revert it at cleanup)"]),
        "bypass": "git commit --no-verify (a scope violation if used; detected by Layer B)",
        "installed_at": now(),
    }


def uninstall_hook(worktree) -> dict:
    worktree = Path(worktree)
    code, out = git(worktree, ["config", "--worktree", "--unset", "core.hooksPath"])
    return {"removed": code == 0, "worktree": str(worktree), "detail": out[:200]}


# --------------------------------------------------------------------------- Layer A: kind plans

KIND_ADAPTERS = {
    "hermes": {
        "supported": True,
        "mechanism": "pre_tool_call hooks: the run-owned `scope-guard.py` hook reads "
                     "`<worktree>/.orchestrator-contract.json` and denies file writes outside "
                     "write_scope — file tools by `file_path`, the shell by redirections/tee/sed -i/"
                     "cp-mv destination — with guard-dangerous and guard-secrets in the same chain",
        "write_boundary": "sub-path",
        "probe_kind": "hook",
        "hook_path_hint": "hooks/scripts/scope-guard.py",
        "verified_on": "hook exercised live on this host: 7/7 direct cases (write/patch inside the "
                       "scope pass; write/patch outside and `echo >> outside` blocked with exit 2; no "
                       "contract file -> exit 0 so normal sessions are untouched) and the full "
                       "dispatcher round-trip via `hermes hooks test pre_tool_call --for-tool "
                       "write_file --payload-file <payload>`: outside -> exit 2 with the Hermes wire "
                       "shape {\"action\": \"block\", ...}, inside -> exit 0. Installing the hook "
                       "needs the user: the agent cannot edit ~/.hermes/config.yaml by design "
                       "(snippet: hooks/configs/hermes.config.snippet.yaml)",
        "probe": None,
        "env_var": None,
        "launch_args": [],
        "notes": "the contract file inside the worktree is what arms the hook; a run that forgets "
                 "`guard --plan --kind hermes` has detection only (commit gate + scope check)",
    },
    "opencode": {
        "supported": True,
        "mechanism": "the run-owned PROJECT config <worktree>/.opencode/opencode.json (edit "
                     "deny-by-default + allow-list, bash deny-by-default, external_directory deny "
                     "with the checkpoint directory allowed), read by opencode from the worker's cwd",
        "write_boundary": "sub-path",
        "verified_on": "opencode 1.18.31 on this host, measured: (a) `opencode debug config` run in "
                       "the worktree WITH NO ENV reports the injected rules; (b) a live `opencode run` "
                       "was refused a write outside the allow-list ('The user has specified a rule "
                       "which prevents you from using this specific tool call') and the file stayed "
                       "unchanged; (c) the deny held against a competing config; (d) a worker "
                       "actually edited its scoped file and committed; (e) with the checkpoint "
                       "directory allowed (pattern '**') the worker wrote its checkpoint OUTSIDE the "
                       "worktree. NOT used: OPENCODE_PERMISSION and OPENCODE_CONFIG_CONTENT are "
                       "inert, and OPENCODE_CONFIG=<file outside the project> makes opencode stop "
                       "matching relative edit patterns — three variants denied even the scoped file.",
        "probe": ["opencode", "debug", "config"],
        "env_var": None,
        "env_is_file": False,
        "notes": "deny rules hold in --auto mode; the shell is a SEPARATE boundary: an edit-only "
                 "boundary was bypassed in a live test by writing through bash, so bash is denied by "
                 "default with the run's own commands allowed",
    },
    "prime": {
        "mechanism": "no path-level write boundary: `-t/--tools` is a TOOL allowlist, not a path "
                     "rule. What it does offer is mechanical EXECUTION control: `--autonomous` with "
                     "`--autonomous-gate <command>` (the run only ends when the gate passes, with "
                     "retries/timeout) and `--autonomous-max-tokens/-max-turns/-timeout-ms` "
                     "(the token budget is enforced by the binary, not by policy text)",
        "write_boundary": "tool-level",
        "verified_on": "prime-agent help (0.5.x on this host): the option surface is tools + "
                       "autonomous gates/limits; there is no permission or sandbox flag, and no "
                       "path-scoped rule in `help`/`help config`",
        "probe": None,
        "env_var": None,
        "supported": False,
        "notes": "NOT SUPPORTED by the orchestrator (target set: opencode, claude, hermes). Kept for "
                 "reference: its `--autonomous-gate` + `--autonomous-max-tokens/-turns` are "
                 "mechanical, but point the gate at something the worker CANNOT write — exercised "
                 "live, it edited the very test the gate ran to make it pass — and keep the commit "
                 "gate and detection in force because the write boundary is absent",
    },
    "codex": {
        "mechanism": "sandbox workspace-write: model shell commands run sandboxed with writable "
                     "roots [workdir, /tmp, $TMPDIR] — a WORKTREE-level boundary at best",
        "write_boundary": "worktree+tmp",
        "verified_on": "codex-cli 0.154.0 prints `sandbox: workspace-write [workdir, /tmp, $TMPDIR]` "
                       "when it starts. Two consequences, both material: it cannot deny a subtree "
                       "of the worktree (no sub-path gate), and a worktree under /tmp — or anywhere "
                       "the worker's TMPDIR points — is NOT confined at all, because /tmp is "
                       "writable by design. `codex exec` did not run non-interactively on this host "
                       "(401 API_KEY_REQUIRED from the configured endpoint), so this is what the "
                       "binary advertises, not a denial exercised live.",
        "probe": None,
        "env_var": None,
        "launch_args": ["-s", "workspace-write", "-C", "{worktree}"],
        "supported": False,
        "notes": "NOT SUPPORTED by the orchestrator (the run target set is opencode, claude and "
                 "hermes). Kept for reference: put worktrees OUTSIDE /tmp if you ever rely on it, "
                 "and expect no sub-path denial — keep the commit gate and detection in force",
    },
    "claude": {
        "supported": True,
        "mechanism": "--settings with permissions.deny/allow using **Edit(path) rules** (Edit covers "
                     "every file-editing tool; `Write(...)` rules are ignored with a warning)",
        "write_boundary": "sub-path",
        "verified_on": "claude 2.1.263 READS AND VALIDATES the settings file: run with a settings "
                       "file containing `Write(...)` rules, the binary reports `Write(**) is not "
                       "matched by file permission checks — only Edit(path) rules are. Use Edit(**) "
                       "instead`, so the file is parsed and the documented syntax is Edit(path). "
                       "The live denial could NOT be exercised on this host: the configured provider "
                       "refuses the connection (`API Error: Connection refused`, "
                       "unrecognized_model deepseek-v4-flash). Claimed as a configured boundary, "
                       "NOT as one exercised in force.",
        "probe": None,
        "env_var": None,
        "notes": "write the settings with Edit(**) deny + Edit(<scope>/**) allow pairs; deny rules "
                 "are documented as enforced in every mode; verify in force the first time a run "
                 "actually uses this kind",
    },
}


def exclude_in_worktree(wt, *patterns: str) -> bool:
    """Add run-owned paths to the worktree's exclude (never the shared config): the guard's
    artifacts must not make the worktree read as dirty for the merge gate."""
    try:
        ex = subprocess.run(["git", "rev-parse", "--git-path", "info/exclude"], cwd=str(wt),
                            capture_output=True, text=True, timeout=30)
        if ex.returncode != 0:
            return False
        path = Path(ex.stdout.strip())
        if not path.is_absolute():
            path = Path(str(wt)) / path
        body = path.read_text(encoding="utf-8", errors="replace") if path.is_file() else ""
        missing = [p for p in patterns if p not in body]
        if not missing:
            return True
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("a", encoding="utf-8") as fh:
            fh.write("\n# run-owned: worker write boundary (.orchestrator guards)\n")
            for p in missing:
                fh.write(p + "\n")
        return True
    except OSError:
        return False


def write_worktree_contract(contract: dict, worktree=None) -> str | None:
    """The contract file that arms the hermes hook, written INSIDE the worktree.

    `scope-guard.py` looks for `.orchestrator-contract.json` walking up from its cwd, so the worker
    only has a boundary while this file is next to it — and the worktree excludes it so it never
    reads as the worker's own output.
    """
    wt = worktree or contract.get("worktree")
    if not wt or not Path(str(wt)).is_dir():
        return None
    payload = {
        "task_id": contract.get("task_id"),
        "repo_root": orchestrator_dir(wt) or "",
        "worktree": str(wt),
        "write_scope": scope_patterns(contract, "write_scope"),
        "forbidden_scope": scope_patterns(contract, "forbidden_scope"),
        "base_commit": contract.get("base_commit"),
        "generated_by": "herdr-orchestrator guard --plan --kind hermes",
    }
    try:
        path = Path(str(wt)) / ".orchestrator-contract.json"
        path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        exclude_in_worktree(wt, ".orchestrator-contract.json", ".checkpoint.json", ".opencode/")
        return str(path)
    except OSError:
        return None


def write_project_permission(contract: dict, permission: dict) -> str | None:
    """Write the run-owned `.opencode/opencode.json` inside the worktree, excluded from git status.

    A generated file that nothing loads is decoration; this one is loaded by opencode because the
    worker's cwd IS the worktree. The file must not make the worktree read as dirty, so it goes into
    the worktree's own exclude (`git rev-parse --git-path info/exclude`), never the shared config.
    """
    wt = contract.get("worktree")
    if not wt or not Path(str(wt)).is_dir():
        return None
    proj = Path(str(wt)) / ".opencode" / "opencode.json"
    try:
        proj.parent.mkdir(parents=True, exist_ok=True)
        proj.write_text(json.dumps({"permission": permission}, indent=2) + "\n", encoding="utf-8")
        exclude_in_worktree(wt, ".opencode/", ".checkpoint.json")
        return str(proj)
    except OSError:
        return None


def orchestrator_dir(anchor) -> str | None:
    """The run's `.orchestrator` directory, found from any path that lives inside the repo.

    The checkpoint protocol writes outside the worktree, so the permission map needs that path in
    absolute form — and it must be derived from the same root the guard was installed from.
    """
    if not anchor:
        return None
    p = Path(str(anchor)).expanduser()
    try:
        p = p.resolve()
    except OSError:
        return None
    for cand in [p, *p.parents]:
        if (cand / ".orchestrator").is_dir():
            return str(cand / ".orchestrator")
    return None


def opencode_permission(contract: dict, *, checkpoint_dir=None) -> dict:
    """Build the opencode permission block: deny every edit, then allow the contracted tree.

    Order matters: opencode resolves the last matching rule, so forbidden_scope denials are written
    after the write_scope allows and therefore win even for a path inside the scope.
    """
    edit = {"*": "deny"}
    for pattern in scope_patterns(contract, "write_scope"):
        if pattern.strip() in ("**", "*"):
            continue
        edit[normalize_pattern(pattern)] = "allow"
        # A bare path means a FILE as often as a directory: `src/stats.py` normalised to
        # `src/stats.py/**` never matches the file, so the worker was denied its own scope and
        # then wrote through the shell. Emit both readings, exactly like path_matches does.
        raw = normalize_pattern(pattern, directory=False)
        if raw != normalize_pattern(pattern):
            edit.setdefault(raw, "allow")
    for pattern in scope_patterns(contract, "forbidden_scope"):
        edit[normalize_pattern(pattern)] = "deny"
        raw = normalize_pattern(pattern, directory=False)
        if raw != normalize_pattern(pattern):
            edit.setdefault(raw, "deny")
    # The shell is a second door to the same filesystem: a live test showed an edit-only boundary
    # being bypassed with `echo >>` (Edit denied, file written anyway). Bash is therefore denied by
    # default too, with only what the run itself needs allowed: git porcelain + the contract's own
    # required checks. Compound commands remain a residual hole (detected by validate-scope and the
    # commit gate, not prevented).
    bash = {"*": "deny"}
    for allowed in ("git status*", "git diff*", "git add*", "git commit*", "git log*",
                    "git rev-parse*", "git show*", "git branch*"):
        bash[allowed] = "allow"
    for check in (contract.get("required_checks") or []):
        cmd = str(check).strip()
        if cmd:
            bash[cmd if cmd.endswith("*") else cmd + "*"] = "allow"
    # Hooks are skippable: `--no-verify`, `-n` and a redirect of core.hooksPath all bypass the
    # run-owned commit gate. Measured: the kit's guard-dangerous already blocks the first two in
    # opencode, and `git -c core.hooksPath=... commit` falls to the `*` deny because it stops
    # matching `git commit*` — but the worker's own config should not depend on the plugin being
    # installed, so the denies are explicit and come after the allows.
    for banned in ("*--no-verify*", "* core.hooksPath*", "*core.hooksPath=*", "git commit -n *"):
        bash[banned] = "deny"
    # Checkpoint INSIDE the worktree: the path a worker picks naturally. Writing outside it turned
    # out to be fragile in three different ways (an approval dialog, a missing parent directory, and
    # a relative path full of `..` that the pattern matcher does not resolve) — a live run showed the
    # worker refused with `Write .../src/calc.py/../../../../../checkpoints/calc.json failed`.
    edit[".checkpoint.json"] = "allow"
    edit.setdefault("./.checkpoint.json", "allow")
    # The checkpoint protocol asks the worker to write OUTSIDE its worktree. Denied, opencode stops
    # at an "Access external directory" dialog and the worker sits there looking alive (live drill:
    # the checkpoint never appeared and the task looked healthy). So the checkpoint directory is the
    # one thing outside the scope that is allowed -- nothing else under .orchestrator/ is.
    external_directory = {"*": "deny"}
    if checkpoint_dir:
        ext = str(checkpoint_dir).rstrip("/") + "/**"
        edit[ext] = "allow"
        external_directory[ext] = "allow"
    return {
        "edit": edit,
        "external_directory": external_directory,
        "bash": bash,
    }


def claude_settings(contract: dict, out_dir) -> Path:
    """Write the run-owned claude settings: Edit(**) deny plus Edit(<scope>/**) allows.

    Measured on claude 2.1.263: the binary parses this file and warns that `Write(...)` rules are
    ignored — "only Edit(path) rules are" matched by file permission checks, and Edit rules cover
    every file-editing tool. Deny rules are documented as enforced in every permission mode.
    """
    allow = []
    for pattern in scope_patterns(contract, "write_scope"):
        p = str(pattern).strip()
        if p in ("**", "*"):
            continue
        allow.append(f"Edit({p})")
        if not p.endswith(("*", "/")):
            allow.append(f"Edit({p}/**)")
    deny = ["Edit(**)"]
    for pattern in scope_patterns(contract, "forbidden_scope"):
        p = str(pattern).strip()
        if p:
            deny.append(f"Edit({p})")
    # the same two doors the opencode boundary closes: hooks are skippable, history is rewritable
    deny += ["Bash(git commit --no-verify:*)", "Bash(git commit -n:*)", "Bash(git push:*)",
             "Bash(git reset --hard:*)"]
    bash_allow = ["Bash(git status:*)", "Bash(git diff:*)", "Bash(git add:*)", "Bash(git commit:*)",
                  "Bash(git log:*)", "Bash(git rev-parse:*)", "Bash(git show:*)"]
    for check in (contract.get("required_checks") or []):
        cmd = str(check).strip()
        if cmd:
            bash_allow.append("Bash(" + (cmd.rstrip("*").rstrip(":") if cmd.endswith("*") else cmd)
                              + ":*)")
    payload = {"permissions": {"deny": deny, "allow": allow + bash_allow, "defaultMode": "default"}}
    path = Path(out_dir) / "claude-settings.json"
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return path


def plan_prevention(contract: dict, kind: str, *, out_dir, worktree=None) -> dict:
    """Write the run-owned guard artifacts for one worker kind. No secrets, no project edits."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    adapter = KIND_ADAPTERS.get(str(kind).lower())
    plan = {
        "task_id": contract.get("task_id"),
        "kind": kind,
        "prevention": "none",
        "mechanism": None,
        "launch_env": {},
        "launch_env_export": [],
        "verification": None,
        "artifacts": [],
        "limitations": [],
        "generated_at": now(),
    }
    if adapter is None:
        plan["limitations"].append(
            f"no verified write-boundary mechanism for kind {kind!r} on this host: the worker keeps "
            f"the whole-worktree boundary only, so out-of-scope writes are caught by detection")
        plan["limitations"].append(
            "a bare 'auto' kind means the guard never looked for an adapter: pass `--kind <the kind "
            "you will launch>` (or record the launch before installing the guard)")
        plan_file = out_dir / "prevention-plan.json"
        plan_file.write_text(json.dumps(plan, indent=2) + "\n", encoding="utf-8")
        plan["artifacts"].append(str(plan_file))
        return plan

    plan["mechanism"] = adapter["mechanism"]
    plan["verified_on"] = adapter["verified_on"]
    if adapter.get("supported") is False:
        plan.update({
            "prevention": "unsupported",
            "limitations": [
                f"kind {kind!r} is NOT a supported run target: the orchestrator covers opencode, "
                f"claude and hermes. Detection (validate-scope) and the commit gate still work, but "
                f"no write boundary is claimed.",
                str(adapter.get("notes") or ""),
            ],
        })
        plan_file = out_dir / "prevention-plan.json"
        plan_file.write_text(json.dumps(plan, indent=2) + "\n", encoding="utf-8")
        plan["artifacts"].append(str(plan_file))
        return plan
    if adapter.get("env_status") == "rejected":
        plan.update({
            "prevention": "none",
            "mechanism": None,
            "launch_env": {},
            "launch_env_export": [],
            "limitations": [
                "the per-kind write boundary cannot be installed: the installed binary version "
                "rejects the generated configuration ("
                + str(adapter.get("env_status_detail") or "unverified") + ")",
                "detection (validate-scope) plus the run-owned commit gate remain in force: "
                "a committing worker is still blocked on an out-of-scope path",
            ],
        })
        plan_file = out_dir / "prevention-plan.json"
        plan_file.write_text(json.dumps(plan, indent=2) + "\n", encoding="utf-8")
        plan["artifacts"].append(str(plan_file))
        return plan
    if adapter.get("probe_kind") == "hook":
        contract_file = write_worktree_contract(contract, worktree=worktree)
        plan.update({
            "prevention": "mechanical" if contract_file else "none",
            "contract_file": contract_file,
            "artifacts": plan["artifacts"] + ([contract_file] if contract_file else []),
            "verification": {
                "exists": True,
                "probe": "hook: scope-guard.py run against a payload outside the scope "
                         "(and `hermes hooks test pre_tool_call --for-tool write_file`)",
                "expect": {"outside_scope": "exit 2 / action: block", "inside_scope": "exit 0"},
            },
            "limitations": [
                "the hook must be registered and approved in the worker's own CLI config "
                "(~/.hermes/config.yaml + consent allowlist): the orchestrator cannot edit that file "
                "by design — see hooks/configs/hermes.config.snippet.yaml",
                "the contract file inside the worktree is what arms the hook; deleting it disarms "
                "the boundary (detection still catches the result)",
                "a compound shell command that writes through a path the parser does not recognise "
                "is a residual hole, caught by validate-scope and the commit gate",
            ] if contract_file else [
                "no worktree recorded: the contract file that arms the hook could not be written, "
                "so this worker has detection only",
            ],
        })
    elif adapter["write_boundary"] == "sub-path" and adapter.get("probe"):
        orch = orchestrator_dir(out_dir)
        # The worker writes its checkpoint into a directory that must already exist: creating it is
        # the orchestrator's job (a missing parent makes the worker's write fail or turn into a
        # permission request, and the task looks alive while nothing progresses).
        if orch:
            (Path(orch) / "checkpoints").mkdir(parents=True, exist_ok=True)
        permission = opencode_permission(
            contract, checkpoint_dir=(str(Path(orch) / "checkpoints") if orch else None))
        permission_file = out_dir / "opencode-permission.json"
        permission_file.write_text(json.dumps({"permission": permission}, indent=2) + "\n",
                                   encoding="utf-8")
        # The binding mechanism is the PROJECT config opencode reads from the worker's own cwd.
        # `OPENCODE_CONFIG` was measured to be WORSE than useless as the primary route: pointing it
        # at a file outside the project makes opencode stop matching the relative `edit` patterns,
        # so the scope allow never lands and even in-scope edits are refused (three live variants,
        # all denied). The generated env file stays on disk for audit, and nothing exports it.
        wt = worktree or contract.get("worktree")
        project_config = write_project_permission({**contract, "worktree": wt}, permission)
        plan.update({
            "prevention": "mechanical",
            "project_config": project_config,
            "permission_file": str(permission_file),
            "launch_env": {},
            "launch_env_export": [],
            "verification": {
                "exists": bool(adapter.get("probe")),
                "probe": adapter.get("probe"),
                "expect": {
                    "edit_default": "deny",
                    "edit_allows": sorted(k for k, v in permission["edit"].items() if v == "allow"),
                    "external_directory_default": "deny",
                },
            },
            "artifacts": [str(permission_file)],
            "limitations": [
                "covers the `edit` tool, external_directory and `bash` (deny-by-default with the "
                "run's own commands allowed); a compound shell command that embeds an allowed prefix "
                "is a residual hole, caught by validate-scope and the commit gate",
                f"the file must reach the worker process: export {adapter['env_var']} with the path "
                f"({permission_file}); verify before dispatch",
            ],
        })
    elif adapter["write_boundary"] == "sub-path" and not adapter.get("probe"):
        settings = claude_settings(contract, out_dir)
        plan.update({
            "prevention": "configured",
            "launch_args": ["--settings", str(settings)],
            "artifacts": plan["artifacts"] + [str(settings)],
            "limitations": [
                "the settings file is parsed and validated by the binary (it reports the Edit(path) "
                "rule syntax), but the denial was not exercised in force on this host: the "
                "configured provider refused the connection. Treat it as configured, not proven, "
                "and exercise it live the first time a run uses this kind",
                "rules are Edit(path): Edit(**) denies every file-editing tool and the contracted "
                "tree is allowed per path; Write(...) rules are ignored by the binary",
                "Bash rules are best-effort prefixes (the agent can build an equivalent command); "
                "the commit gate and the post-hoc scope check stay in force",
            ],
        })
    elif adapter["write_boundary"] in ("worktree", "worktree+tmp"):
        limits = ["writes are confined to the worktree, not to write_scope: an out-of-scope path "
                  "inside the worktree is still possible and is caught by detection"]
        if adapter["write_boundary"] == "worktree+tmp":
            limits.append("the sandbox also writable-roots /tmp and $TMPDIR by design: a worktree "
                          "under /tmp is not confined at all, so keep run worktrees outside /tmp "
                          "when you rely on this")
        plan.update({
            "prevention": "coarse",
            "launch_args": [str(a).format(worktree=str(worktree or contract.get("worktree") or ""))
                            for a in (adapter.get("launch_args") or [])],
            "limitations": limits,
        })
    elif adapter["write_boundary"] == "tool-level":
        plan.update({
            "prevention": "none",
            "limitations": [
                "no path-level write boundary in this kind: `-t/--tools` restricts WHICH tools run, "
                "not where they write",
                "what it does offer is mechanical control of execution: use --autonomous with "
                "--autonomous-gate <required check> and the --autonomous-max-tokens/-turns/-timeout "
                "limits as the run's budget",
            ],
        })
    else:
        plan.update({
            "prevention": "none",
            "limitations": ["sub-path write denial not verified for this kind on this host: "
                            "detection + commit gate only"],
        })
    plan_file = out_dir / "prevention-plan.json"
    plan_file.write_text(json.dumps(plan, indent=2) + "\n", encoding="utf-8")
    plan["artifacts"].append(str(plan_file))
    return plan


def verify_hook_probe(contract: dict, adapter: dict, result: dict, worktree, cwd) -> dict:
    """Prove a hook-based boundary in force: the hook is registered, and it actually blocks.

    Two cases are run against the real hook binary: a path outside write_scope must exit 2 and a
    path inside must exit 0. Both need the contract file the orchestrator wrote in the worktree —
    without it the hook stays silent on purpose.
    """
    # the kit root is whichever ancestor actually holds the hook (never a hardcoded depth)
    hint = str(adapter.get("hook_path_hint") or "hooks/scripts/scope-guard.py")
    here = Path(__file__).resolve()
    kit = next((base for base in [here, *here.parents] if (base / hint).is_file()), None)
    hook = (kit / hint) if kit else (here.parent / hint)
    wt = worktree or contract.get("worktree")
    result["hook"] = str(hook) if hook.is_file() else None
    if not hook.is_file():
        result["reasons"].append(f"hook script not found in the kit: {hook}")
        return result
    if not wt:
        result["reasons"].append("no worktree recorded: nothing to arm the hook against")
        return result
    if not (Path(str(wt)) / ".orchestrator-contract.json").is_file():
        result["reasons"].append("the worktree has no .orchestrator-contract.json: run "
                                 "`guard --plan --kind hermes` first (the hook is silent without it)")
        return result
    try:
        proc = subprocess.run(["hermes", "hooks", "list"], capture_output=True, text=True, timeout=60)
        registered = proc.returncode == 0 and "scope-guard.py" in proc.stdout
    except (OSError, subprocess.TimeoutExpired) as exc:
        registered = False
        result["reasons"].append(f"could not read the hook registry: {exc}")
    result["registered"] = registered
    if not registered:
        result["reasons"].append(
            "the hook is not registered in the worker's CLI config (the agent cannot edit "
            "~/.hermes/config.yaml by design): merge hooks/configs/hermes.config.snippet.yaml, "
            "approve it at session start, and re-run")
    pats = scope_patterns(contract, "write_scope")
    inside_rel = None
    if pats:
        p = str(pats[0]).strip().rstrip("/")
        inside_rel = p.replace("**", "probe-escopo.txt").replace("*", "probe-escopo.txt") if any(
            ch in p for ch in "*?[") else p
    cases = [("outside", "fora-do-escopo.txt", 2)]
    if inside_rel:
        cases.append(("inside", inside_rel, 0))
    result["cases"] = {}
    import os as _os
    for label, rel, expected in cases:
        payload = {"tool_name": "write_file", "cwd": str(wt),
                   "tool_input": {"file_path": str(Path(str(wt)) / rel), "content": "probe"}}
        try:
            run = subprocess.run(["python3", str(hook)], input=json.dumps(payload),
                                 capture_output=True, text=True, timeout=60, cwd=str(wt))
            rc = run.returncode
        except (OSError, subprocess.TimeoutExpired):
            rc = None
        result["cases"][label] = rc
        if rc != expected:
            result["reasons"].append(f"hook case {label!r} ({rel}) exited {rc}, expected {expected}")
    result["verified"] = not result["reasons"]
    return result


def verify_launch(contract: dict, kind: str, *, cwd=None, observed: str | None = None,
                  worktree=None) -> dict:
    """Prove the prevention is actually in force before the worker is trusted.

    - `observed` given: compare it against the intended payload (the orchestrator echoes the worker's
      environment in its shell and passes the real output here).
    - otherwise: run the kind's own probe (`opencode debug config`) under the intended environment
      and assert the effective rules deny by default and still allow the contracted scope.
    """
    kind = str(kind).lower()
    adapter = KIND_ADAPTERS.get(kind)
    result = {"kind": kind, "task_id": contract.get("task_id"), "verified": False,
              "mechanism": adapter["mechanism"] if adapter else None, "reasons": [],
              "observed": None, "verified_at": now()}
    if adapter is not None and adapter.get("probe_kind") == "hook":
        return verify_hook_probe(contract, adapter, result, worktree, cwd)
    if adapter is not None and adapter.get("supported") is False:
        result["reasons"].append(
            f"{kind} is not a supported run target (opencode, claude and hermes are): "
            f"no write boundary is claimed for it. {str(adapter.get('notes'))[:160]}")
        return result
    if adapter is None or not (adapter.get("probe") or adapter.get("env_var")):
        if adapter:
            result["reasons"].append(
                f"{kind}: no probe command exists for this kind, so the boundary cannot be verified "
                f"at launch. Boundary level: {adapter['write_boundary']!r}; the plan carries the "
                f"launch args to pass. Evidence on record: {str(adapter.get('verified_on'))[:160]}")
        else:
            result["reasons"].append(f"no write-boundary mechanism is known for kind {kind!r} "
                                     f"(detection + commit gate only)")
        return result

    wt = worktree or contract.get("worktree")
    orch = orchestrator_dir(wt or cwd)
    permission = opencode_permission(
        contract, checkpoint_dir=(str(Path(orch) / "checkpoints") if orch else None))
    intended = json.dumps(permission, separators=(",", ":"))

    if observed is not None:
        text = observed.strip().strip("'\"")
        try:
            got = json.loads(text)
        except ValueError:
            result["reasons"].append("observed environment value is not valid JSON")
            return result
        result["observed"] = got
        if adapter.get("env_status") == "rejected":
            result["reasons"].append(
                "this kind/version rejects the generated environment ("
                + str(adapter.get("env_status_detail") or "unverified")
                + "): record prevention as none instead of launch args")
            result["verified"] = False
            return result
        edit = got.get("edit") if isinstance(got, dict) else None
        if not isinstance(edit, dict):
            result["reasons"].append("observed value carries no edit rule map")
            result["verified"] = False
            return result
        if edit.get("*") != "deny":
            result["reasons"].append("observed edit rules do not deny by default")
        for pattern in scope_patterns(contract, "write_scope"):
            if pattern.strip() in ("**", "*"):
                continue
            if edit.get(normalize_pattern(pattern)) != "allow":
                result["reasons"].append(f"observed rules do not allow {pattern!r}")
        result["verified"] = not result["reasons"]
        return result

    probe = adapter.get("probe")
    if not probe:
        result["reasons"].append("no probe command for this kind")
        return result
    import os
    # The project config IS the mechanism: probe with NO ENV, in the worktree itself. Measured: an
    # env var pointing the config at a file outside the project makes opencode stop matching the
    # relative edit patterns, so even in-scope writes get refused.
    env = {k: v for k, v in os.environ.items()
           if k not in ("OPENCODE_CONFIG", "OPENCODE_PERMISSION", "OPENCODE_CONFIG_CONTENT")}
    proj_config = (Path(str(wt)) / ".opencode" / "opencode.json") if wt else None
    result["project_config"] = str(proj_config) if proj_config and proj_config.is_file() else None
    if proj_config is None or not proj_config.is_file():
        result["reasons"].append("the run-owned project config is not in the worktree: nothing "
                                 "carries the boundary into the worker (guard --plan writes it)")
        return result
    try:
        proc = subprocess.run(probe, cwd=str(cwd) if cwd else None, capture_output=True, text=True,
                              timeout=120, env=env)
    except (OSError, subprocess.TimeoutExpired) as exc:
        result["reasons"].append(f"probe failed to run: {exc}")
        return result
    if proc.returncode != 0:
        result["reasons"].append(f"probe exited {proc.returncode}: {(proc.stderr or '')[:160]}")
        return result
    try:
        effective = json.loads(proc.stdout)
    except ValueError:
        result["reasons"].append("probe output is not JSON")
        return result
    effective_perm = effective.get("permission") or {}
    result["observed"] = effective_perm
    edit = effective_perm.get("edit")
    if not isinstance(edit, dict) or edit.get("*") != "deny":
        result["reasons"].append("effective config does not deny edits by default")
    else:
        for pattern in scope_patterns(contract, "write_scope"):
            if pattern.strip() in ("**", "*"):
                continue
            if edit.get(normalize_pattern(pattern)) != "allow":
                result["reasons"].append(f"effective config does not allow {pattern!r}")
    if effective_perm.get("external_directory") and \
            effective_perm["external_directory"].get("*") != "deny":
        result["reasons"].append("effective config does not deny external directories")
    if orch:
        ck_glob = str(Path(orch) / "checkpoints" / "**")
        if (effective_perm.get("edit") or {}).get(ck_glob) != "allow":
            result["reasons"].append("effective config does not allow the checkpoint directory "
                                     "(the worker would stop at an approval dialog)")
    result["verified"] = not result["reasons"]
    return result


# --------------------------------------------------------------------------- CLI

def _repo(a) -> Path:
    """Resolve the repository root: a subcommand-level --repo wins over the global one."""
    return Path(a.repo or getattr(a, "global_repo", ".")).expanduser().resolve()


def _load_contract(a) -> dict:
    repo = _repo(a)
    contract = resolve_contract(repo, a.contract, a.task_id)
    if a.worktree:
        contract["worktree"] = str(Path(a.worktree).expanduser().resolve())
    return contract


def cmd_check(a) -> int:
    repo = _repo(a)
    worktree = Path(a.worktree).expanduser().resolve() if a.worktree else repo
    contract = _load_contract(a)
    result = check_scope(contract, repo=worktree, base=a.base or contract.get("base_commit"),
                         head=a.head, include_dirty=a.include_dirty)
    if a.json:
        print(json.dumps(result, indent=2))
    else:
        print(render_check(result))
    return 0 if result.get("status") == "PASS" else 1


def cmd_staged(a) -> int:
    repo = Path(a.worktree).expanduser().resolve() if a.worktree else Path(a.repo).expanduser().resolve()
    contract = _load_contract(a)
    code, paths, err = staged_paths(repo)
    if code != 0:
        result = {"status": "UNKNOWN", "error": f"git diff --cached failed: {err[:200]}",
                  "task_id": contract.get("task_id")}
    else:
        cls = classify_paths(paths, contract)
        result = {"status": "PASS" if not cls["violations"] else "FAIL",
                  "task_id": contract.get("task_id"), "changed": sorted(paths), **cls,
                  "checked_at": now()}
    if a.json:
        print(json.dumps(result, indent=2))
    else:
        print(render_check({**result, "base": "(staged index)", "head": "(staged index)"}))
    return 0 if result.get("status") == "PASS" else 1


def cmd_validate_contract(a) -> int:
    contract = _load_contract(a)
    verdict = validate_contract(contract)
    if a.json:
        print(json.dumps(verdict, indent=2))
    else:
        print("TASK_CONTRACT: VALID" if verdict["valid"] else "TASK_CONTRACT: INVALID")
        for e in verdict["errors"]:
            print(f"  error: {e}")
        for w in verdict["warnings"]:
            print(f"  warning: {w}")
    return 0 if verdict["valid"] else 1


def cmd_install_hook(a) -> int:
    repo = _repo(a)
    worktree = Path(a.worktree).expanduser().resolve()
    contract = _load_contract(a)
    result = install_hook(contract, worktree, repo, guards_dir=a.guards_dir,
                          hooks_dir=a.hooks_dir)
    print(json.dumps(result, indent=2))
    return 0 if result.get("installed") else 1


def cmd_uninstall_hook(a) -> int:
    print(json.dumps(uninstall_hook(Path(a.worktree).expanduser().resolve()), indent=2))
    return 0


def cmd_plan(a) -> int:
    repo = _repo(a)
    contract = _load_contract(a)
    out = Path(a.out).expanduser() if a.out else \
        repo / ".orchestrator" / "guards" / str(contract.get("task_id") or "task")
    plan = plan_prevention(contract, a.kind, out_dir=out)
    print(json.dumps(plan, indent=2))
    return 0 if plan["prevention"] != "none" else 0


def cmd_verify_launch(a) -> int:
    repo = _repo(a)
    contract = _load_contract(a)
    result = verify_launch(contract, a.kind, cwd=a.cwd or contract.get("worktree"),
                           observed=a.observed)
    print(json.dumps(result, indent=2))
    return 0 if result["verified"] else 1


def cmd_adapters(a) -> int:
    payload = {k: {"mechanism": v["mechanism"], "write_boundary": v["write_boundary"],
                   "verified_on": v["verified_on"], "env_var": v["env_var"]}
               for k, v in KIND_ADAPTERS.items()}
    if a.json:
        print(json.dumps(payload, indent=2))
    else:
        for kind, info in payload.items():
            print(f"{kind:<10} boundary={info['write_boundary']:<10} {info['mechanism']}")
            print(f"           verified: {info['verified_on']}")
        print(f"{'*':<10} boundary=none       detection + commit gate only")
    return 0


def cmd_glob(a) -> int:
    ok = path_matches(a.path, a.pattern)
    print(f"{'MATCH' if ok else 'NO MATCH'}  {a.pattern}  vs  {a.path}")
    return 0 if ok else 1


def main() -> int:
    p = argparse.ArgumentParser(description="Deterministic scope enforcement (contract-driven)")
    p.add_argument("--repo", dest="global_repo", default=".",
                   help="repository root (default: cwd); subcommands also accept --repo")
    sub = p.add_subparsers(dest="cmd", required=True)

    def add_contract_args(sp):
        sp.add_argument("--repo", help="repository root (default: the global --repo)")
        sp.add_argument("--contract", help="contract file (JSON or the YAML subset)")
        sp.add_argument("--task-id", help="load .orchestrator/contracts/<task-id>.*")
        sp.add_argument("--worktree", help="worktree to run git in (default: --repo)")

    s = sub.add_parser("check")
    add_contract_args(s)
    s.add_argument("--base", help="base ref (default: contract base_commit)")
    s.add_argument("--head", help="head ref (default: contract branch or HEAD)")
    s.add_argument("--include-dirty", action="store_true", help="also count uncommitted paths")
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_check)

    s = sub.add_parser("staged")
    add_contract_args(s)
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_staged)

    s = sub.add_parser("validate-contract")
    add_contract_args(s)
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_validate_contract)

    s = sub.add_parser("install-hook")
    s.add_argument("--contract")
    s.add_argument("--task-id")
    s.add_argument("--worktree", required=True)
    s.add_argument("--guards-dir")
    s.add_argument("--hooks-dir")
    s.set_defaults(func=cmd_install_hook)

    s = sub.add_parser("uninstall-hook")
    s.add_argument("--worktree", required=True)
    s.set_defaults(func=cmd_uninstall_hook)

    s = sub.add_parser("plan")
    add_contract_args(s)
    s.add_argument("--kind", required=True)
    s.add_argument("--out")
    s.set_defaults(func=cmd_plan)

    s = sub.add_parser("verify-launch")
    add_contract_args(s)
    s.add_argument("--kind", required=True)
    s.add_argument("--cwd")
    s.add_argument("--observed", help="the worker environment value captured by the orchestrator")
    s.set_defaults(func=cmd_verify_launch)

    s = sub.add_parser("adapters")
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_adapters)

    s = sub.add_parser("glob")
    s.add_argument("--pattern", required=True)
    s.add_argument("--path", required=True)
    s.set_defaults(func=cmd_glob)

    a = p.parse_args()
    try:
        return a.func(a)
    except (FileNotFoundError, ValueError) as exc:
        print(str(exc), file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
